"""Module containing the allowed literal values for various field types"""
from enum import Enum


class DischargeDispositionValue(Enum):
    """Allowed values for patient discharge dispositions"""

    HOME_OR_SELF_CARE = 1
    STCH = 2
    SNF = 3
    ICF = 4
    CUSTODIAL_SUPPORTIVE_CARE = 4
    ANOTHER_TYPE_OF_FACILITY = 5
    CANCER_OR_CHILDREN_HOSPITAL = 5
    HOME_HEALTH_SERVICES = 6
    AGAINST_MEDICAL_ADVICE = 7
    HOME_IV_SERVICE = 8
    DIED = 20
    TRANSFER_TO_COURT_OR_LAW_ENFORCEMENT = 21
    STILL_A_PATIENT = 30
    FEDERAL_HOSPITAL = 43
    HOSPICE_HOME = 50
    HOSPICE_MEDICAL_FACILITY = 51
    SWING_BED = 61
    REHAB_FACILITY_OR_UNIT = 62
    LTC_HOSPITAL = 63
    MEDICARE_CERTIFIED_NURSING_FACILITY = 64
    PSYCHIATRIC_HOSPITAL = 65
    CRITICAL_ACCESS_HOSPITAL = 66
    DESIGNATED_DISASTER_ALTERNATIVE_CARE = 69
    OTHER_INSTITUTION = 70
    OP_SERVICES_OTHER_FACILITY = 71
    OP_SERVICES_THIS_FACILITY = 72
    HOME_SELF_CARE_WITH_PLANNED_READMISSION = 81
    STCH_WITH_PLANNED_READMISSION = 82
    SNF_WITH_PLANNED_READMISSION = 83
    CUSTODIAL_SUPPORTIVE_CARE_WITH_PLANNED_READMISSION = 84
    CANCER_OR_CHILDREN_HOSPITAL_WITH_PLANNED_READMISSION = 85
    HOME_HEALTH_SERVICES_WITH_PLANNED_READMISSION = 86
    TRANSFER_TO_COURT_OR_LAW_ENFORCEMENT_WITH_PLANNED_READMISSION = 87
    FEDERAL_HOSPITAL_WITH_PLANNED_READMISSION = 88
    SWING_BED_WITH_PLANNED_READMISSION = 89
    REHAB_FACILITY_OR_UNIT_WITH_PLANNED_READMISSION = 90
    LTC_HOSPITAL_WITH_PLANNED_READMISSION = 91
    MEDICARE_CERTIFIED_NURSING_FACILITY_WITH_PLANNED_READMISSION = 92
    PSYCHIATRIC_HOSPITAL_WITH_PLANNED_READMISSION = 93
    CRITICAL_ACCESS_HOSPITAL_WITH_PLANNED_READMISSION = 94
    OTHER_INSTITUTION_WITH_PLANNED_READMISSION_WITH_PLANNED_READMISSION = 95


class PayerValue(Enum):
    """Allowed Payer values"""

    MEDICARE = 1
    MEDICAID = 2
    TITLE_V = 3
    OTHER_GOVERNMENT = 4
    WORKERS_COMPENSATION = 5
    BLUE_CROSS = 6
    INSURANCE_COMPANY = 7
    SELF_PAY = 8
    OTHER = 9
    NO_CHARGE = 10


class SexValue(Enum):
    """Allowed Sex values"""

    UNKNOWN = 0
    MALE = 1
    FEMALE = 2


class PresentOnAdmissionValue(Enum):
    """Allowed Present on Admission values"""

    YES = "Y"
    NO = "N"
    CLINICALLY_UNABLE_TO_DETERMINE = "W"
    INSUFFICIENT_DOCUMENTATION_TO_DETERMINE = "U"
    EXEMPT = "1"
    NONE_TYPE = " "


class ApplyHACLogicValue(Enum):
    """Allowed ApplyHACLogic value"""

    EXEMPT_FROM_POA_REPORTING = "X"
    REQUIRES_POA_REPORTING = "Y"
