"""Module containing the allowed literal values for various field types"""
from enum import Enum


class DischargeDispositionValue(Enum):
    """Allowed values for patient discharge dispositions"""

    HOME_OR_SELF_CARE = 1
    STCH = 2
    SNF = 3
    ICF = 4
    CUSTODIAL_SUPPORTIVE_CARE = 4
    ANOTHER_TYPE_OF_FACILITY = 5
    CANCER_OR_CHILDREN_HOSPITAL = 5
    HOME_HEALTH_SERVICES = 6
    AGAINST_MEDICAL_ADVICE = 7
    HOME_IV_SERVICE = 8
    DIED = 20
    TRANSFER_TO_COURT_OR_LAW_ENFORCEMENT = 21
    STILL_A_PATIENT = 30
    FEDERAL_HOSPITAL = 43
    HOSPICE_HOME = 50
    HOSPICE_MEDICAL_FACILITY = 51
    SWING_BED = 61
    REHAB_FACILITY_OR_UNIT = 62
    LTC_HOSPITAL = 63
    MEDICARE_CERTIFIED_NURSING_FACILITY = 64
    PSYCHIATRIC_HOSPITAL = 65
    CRITICAL_ACCESS_HOSPITAL = 66
    DESIGNATED_DISASTER_ALTERNATIVE_CARE = 69
    OTHER_INSTITUTION = 70
    OP_SERVICES_OTHER_FACILITY = 71
    OP_SERVICES_THIS_FACILITY = 72
    HOME_SELF_CARE_WITH_PLANNED_READMISSION = 81
    STCH_WITH_PLANNED_READMISSION = 82
    SNF_WITH_PLANNED_READMISSION = 83
    CUSTODIAL_SUPPORTIVE_CARE_WITH_PLANNED_READMISSION = 84
    CANCER_OR_CHILDREN_HOSPITAL_WITH_PLANNED_READMISSION = 85
    HOME_HEALTH_SERVICES_WITH_PLANNED_READMISSION = 86
    TRANSFER_TO_COURT_OR_LAW_ENFORCEMENT_WITH_PLANNED_READMISSION = 87
    FEDERAL_HOSPITAL_WITH_PLANNED_READMISSION = 88
    SWING_BED_WITH_PLANNED_READMISSION = 89
    REHAB_FACILITY_OR_UNIT_WITH_PLANNED_READMISSION = 90
    LTC_HOSPITAL_WITH_PLANNED_READMISSION = 91
    MEDICARE_CERTIFIED_NURSING_FACILITY_WITH_PLANNED_READMISSION = 92
    PSYCHIATRIC_HOSPITAL_WITH_PLANNED_READMISSION = 93
    CRITICAL_ACCESS_HOSPITAL_WITH_PLANNED_READMISSION = 94
    OTHER_INSTITUTION_WITH_PLANNED_READMISSION_WITH_PLANNED_READMISSION = 95


class PayerValue(Enum):
    """Allowed Payer values"""

    MEDICARE = 1
    MEDICAID = 2
    TITLE_V = 3
    OTHER_GOVERNMENT = 4
    WORKERS_COMPENSATION = 5
    BLUE_CROSS = 6
    INSURANCE_COMPANY = 7
    SELF_PAY = 8
    OTHER = 9
    NO_CHARGE = 10


class SexValue(Enum):
    """Allowed Sex values"""

    UNKNOWN = 0
    MALE = 1
    FEMALE = 2


class PresentOnAdmissionValue(Enum):
    """Allowed Present on Admission values"""

    YES = "Y"
    NO = "N"
    CLINICALLY_UNABLE_TO_DETERMINE = "W"
    INSUFFICIENT_DOCUMENTATION_TO_DETERMINE = "U"
    EXEMPT = "1"
    NONE_TYPE = " "


class ApplyHACLogicValue(Enum):
    """Allowed ApplyHACLogic value"""

    EXEMPT_FROM_POA_REPORTING = "X"
    REQUIRES_POA_REPORTING = "Y"


class MedicalSurgicalIndicatorValue(Enum):
    """Medical Surgical DRG Indicator values"""

    DRGReturnCodeNotZero = 0
    MedicalDRG = 1
    SurgicalDRG = 2


class DRGReturnCodeValue(Enum):
    """DRG Return Code values"""

    OK_DRG_ASSIGNED = 0
    DIAGNOSIS_CODE_CANNOT_BE_USED_AS_PDX = 1
    RECORD_DOES_NOT_MEET_CRITERIA_FOR_ANY_DRG = 2
    INVALID_AGE = 3
    INVALID_SEX = 4
    INVALID_DISCHARGE_STATUS = 5
    ILLOGICAL_PDX = 10
    HAC_POA_LOGIC_NON_EXEMPT_AND_MISSING_OR_INVALID = 12
    HAC_POA_ARE_N_OR_U = 13
    HAC_POA_ARE_INVALID_MISSING_OR_1 = 14
    HAC_POA_MULTIPLE_DISTINCT_HAC_POAS_NOT_Y_OR_W = 15


class MSGMCEEditReturnCodeValue(Enum):
    """MSG/MCE Edit Record Code values"""

    MCE_NO_ERRORS_FOUND = 0
    MCE_PRE_PAYMENT_ERROR = 1
    MCE_POST_PAYMENT_ERROR = 2
    MCE_PRE_AND_POST_PAYMENT_ERROR = 3
    MCE_INVALID_DISCHARGE_DATE = 4


class PrincipalDiagnosisEditReturnFlagValue(Enum):
    """Principal diagnosis edit return flag"""

    DIAGNOSIS_NOT_USED_TO_ASSIGN_DRG = 0
    INVALID_DIAGNOSIS_CODE = 1
    SEX_CONFLICT = 2
    NOT_APPLICABLE_FOR_PRINCIPAL_DIAGNOSIS = 3
    AGE_CONFLICT = 4
    V_W_X_OR_Y_CODE_AS_PRINCIPAL_DIAGNOSIS = 5
    NON_SPECIFIC_PRINCIPAL_DIAGNOSIS = 6
    MANIFESTATION_CODE_AS_PRINCIPAL_DIAGNOSIS = 7
    QUESTIONABLE_ADMISSION = 8
    UNACCEPTABLE_PRINCIPAL_DIAGNOSIS = 9
    SECONDARY_DIAGNOSIS_REQUIRED = 10
    PRINCIPAL_DIAGNOSIS_IS_ITS_OWN_CC = 11
    DIAGNOSIS_AFFECTED_BOTH_INITIAL_AND_FINAL_DRG_ASSIGNMENT = 12
    MSP_ALERT = 13
    PRINCIPAL_DIAGNOSIS_IS_ITS_OWN_MCC = 14
    DIAGNOSIS_AFFECTED_THE_FINAL_DRG_ONLY = 15
    DIAGNOSIS_AFFECTED_THE_INITIAL_DRG_ONLY = 16
    DIAGNOSIS_IS_AN_MCC_FOR_INITIAL_DRG_AND_A_NON_CC_FOR_FINAL_DRG = 17
    DIAGNOSIS_IS_A_CC_FOR_INITIAL_DRG_AND_A_NON_CC_FOR_FINAL_DRG = 18
    WRONG_PROCEDURE_PERFORMED = 19
    UNSPECIFIED_CODE = 20
    DIAGNOSIS_IS_A_CC_BUT_NOT_CONSIDERED_DUE_TO_PDX_SDX_EXCLUSION = 21
    DIAGNOSIS_IS_AN_MCC_BUT_NOT_CONSIDERED_DUE_TO_PDX_SDX_EXCLUSION = 22
    PRINCIPAL_DIAGNOSIS_PART_OF_HAC_ASSIGNMENT_CRITERIA = 99


class PrincipalDiagnosisHospitalAcquiredConditionAssignmentCriteriaValue(Enum):
    """Principal diagnosis HAC assignment criteria values"""

    CRITERIA_TO_BE_ASSIGNED_AS_A_HAC_NOT_MET = "00"
    INFECTION_AFTER_BARIATRIC_SURGERY = "11"
    DIAGNOSIS_WAS_NOT_CONSIDERED_BY_GROUPER = "  "


class DiagnosisHospitalAcquiredConditionUsageValue(Enum):
    """Principal and Secondary Diagnosis hospital acquire condition usage values"""

    HAC_NOT_APPLICABLE = "0"
    HAC_CRITERIA_MET = "1"
    DX_ON_HAC_LIST_BUT_HAC_NOT_APPLICABLE_DUE_TO_PDX_SDX_EXCLUSION = "3"
    HAC_NOT_APPLICABLE_HOSPITAL_IS_EXEMPT_FROM_POA_REPORTING = "4"
    DIAGNOSIS_WAS_NOT_CONSIDERED_BY_GROUPER = " "


class SecondaryDiagnosisEditReturnFlagValue(Enum):
    """Secondary diagnosis edit return flag"""

    DIAGNOSIS_NOT_USED_TO_ASSIGN_DRG = 0
    INVALID_DIAGNOSIS_CODE = 1
    SEX_CONFLICT = 2
    DUPLICATE_OF_PRINCIPAL_DIAGNOSIS = 3
    AGE_CONFLICT = 4
    SECONDARY_DIAGNOSIS_IS_A_CC = 11
    DIAGNOSIS_AFFECTED_BOTH_INITIAL_AND_FINAL_DRG_ASSIGNMENT = 12
    MSP_ALERT = 13
    SECONDARY_DIAGNOSIS_IS_AN_MCC = 14
    DIAGNOSIS_AFFECTED_THE_FINAL_DRG_ONLY = 15
    DIAGNOSIS_AFFECTED_THE_INITIAL_DRG_ONLY = 16
    DIAGNOSIS_IS_AN_MCC_FOR_INITIAL_DRG_AND_A_NON_CC_FOR_FINAL_DRG = 17
    DIAGNOSIS_IS_A_CC_FOR_INITIAL_DRG_AND_A_NON_CC_FOR_FINAL_DRG = 18
    WRONG_PROCEDURE_PERFORMED = 19
    UNSPECIFIED_CODE = 20
    DIAGNOSIS_IS_A_CC_BUT_NOT_CONSIDERED_DUE_TO_PDX_SDX_EXCLUSION = 21
    DIAGNOSIS_IS_AN_MCC_BUT_NOT_CONSIDERED_DUE_TO_PDX_SDX_EXCLUSION = 22
    SECONDARY_DIAGNOSIS_IS_A_HAC = 99


class SecondaryDiagnosisHospitalAcquiredConditionAssignmentCriteriaValue(Enum):
    """Secondary diagnosis HAC assignment criteria values"""

    CRITERIA_TO_BE_ASSIGNED_AS_A_HAC_NOT_MET = "00"
    FOREIGN_OBJECT_RETAINED_AFTER_SURGERY = "01"
    AIR_EMBOLISM = "02"
    BLOOD_INCOMPATIBILITY = "03"
    PRESSURE_ULCERS = "04"
    FALLS_AND_TRAUMA = "05"
    CATHETER_ASSOCIATED_UTI = "06"
    VASCULAR_CATHETER_ASSOCIATED_INFECTION = "07"
    INFECTION_AFTER_CABG = "08"
    MANIFESTATIONS_OF_POOR_GLYCEMIC_CONTROL = "09"
    DVT_PE_AFTER_KNEE_OR_HIP_REPLACEMENT = "10"
    INFECTION_AFTER_BARIATRIC_SURGERY = "11"
    INFECTION_AFTER_CERTAIN_ORTHOPEDIC_PROCEDURES_OF_SPINE_SHOULDER_AND_ELBOW = "12"
    SURGICAL_SITE_INFECTION_FOLLOWING_CARDIAC_IMPLANTABLE_ELECTRONIC_DEVICE_PROCEDURES = (
        "13"
    )
    IATROGENIC_PNEUMOTHORAX_WITH_CATHETERIZATION = "14"
    DIAGNOSIS_WAS_NOT_CONSIDERED_BY_GROUPER = "  "


class ProcedureEditReturnFlagValue(Enum):
    """Procedure Edit Return Flag"""

    PROCEDURE_DID_NOT_AFFECT_DRG = "00"
    INVALID_PROCEDURE_CODE = "01"
    SEX_CONFLICT = "02"
    PROCEDURE_AFFECTED_BOTH_INITIAL_AND_FINAL_DRG_ASSIGNMENT = "12"
    PROCEDURE_AFFECTED_THE_FINAL_DRG_ASSIGNMENT_ONLY = "15"
    PROCEDURE_AFFECTED_INITIAL_DRG_ASSIGNMENT_ONLY = "16"
    PROCEDURE_IS_AN_OR_PROCEDURE = "20"
    NON_SPECIFIC_OR_PROCEDURE = "21"
    OPEN_BIOPSY_CHECK = "22"
    NON_COVERED_PROCEDURE = "23"
    BILATERAL_PROCEDURE = "24"
    LIMITED_COVERAGE = "30"
    QUESTIONABLE_OBSTETRIC_ADMISSION = "31"
    PROCEDURE_INCONSISTENT_WITH_LOS = "40"
    PROCEDURE_PART_OF_HAC_ASSIGNMENT_CRITERIA = "99"


class ProcedureHospitalAcquiredConditionAssignmentCriteriaValue(Enum):
    """Procedure Hospital Acquired Condition Assignment Criteria"""

    CRITERIA_TO_BE_ASSIGNED_AS_A_HAC_NOT_MET = "00"
    INFECTION_AFTER_CABG = "08"
    DVT_PE_AFTER_KNEE_OR_HIP_REPLACEMENT = "10"
    INFECTION_AFTER_BARIATRIC_SURGERY = "11"
    INFECTION_AFTER_CERTAIN_ORTHOPEDIC_PROCEDURES_OF_SPINE_SHOULDER_AND_ELBOW = "12"
    SURGICAL_SITE_INFECTION_FOLLOWING_CARDIAC_IMPLANTABLE_ELECTRONIC_DEVICE_PROCEDURES = (
        "13"
    )
    IATROGENIC_PNEUMOTHORAX_WITH_CATHETERIZATION = "14"
    DIAGNOSIS_WAS_NOT_CONSIDERED_BY_GROUPER = "  "


class DRGCCMCCUsageValue(Enum):
    """DRG CC/MCC Usage"""

    DRG_ASSIGNED_IS_NOT_BASED_ON_THE_PRESENCE_OF_CC_OR_MCC = 0
    DRG_ASSIGNED_IS_BASED_ON_THE_PRESENCE_OF_MCC = 1
    DRG_ASSIGNED_IS_BASED_ON_THE_PRESENCE_OF_CC = 2


class HACStatusValue(Enum):
    """Hospital Acquire Condition Status"""

    HAC_STATUS_NOT_APPLICABLE = 0
    HAC_STATUS_ONE_OR_MORE_HAC_CRITERIA_MET_FINAL_DRG_DOES_NOT_CHANGE = 1
    HAC_STATUS_ONE_OR_MORE_HAC_CRITERIA_MET_FINAL_DRG_CHANGES = 2
    HAC_STATUS_ONE_OR_MORE_HAC_CRITERIA_MET_FINAL_DRG_CHANGES_TO_UNGROUPABLE = 3
